/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package monproj;
import net.lingala.zip4j.*;

import net.lingala.zip4j.exception.ZipException;
import net.lingala.zip4j.model.ZipParameters;
import net.lingala.zip4j.model.enums.CompressionMethod;
import org.apache.commons.cli.*;



import java.io.File;

public class App {
    public String getGreeting() {
        return "Hello fouad.";
    }

    public static void main(String[] args) throws ZipException, ParseException {





        Options Opt = new Options();

        // add options
        Opt.addOption("c",true,"compreser");
        Opt.addOption("x",true,"extract");
        Opt.addOption("help",false,"manuel");

        CommandLine Line= null;
        CommandLineParser parser = new DefaultParser();
        // Parse Line
        try {
            Line = parser.parse(Opt,args);

        }catch (ParseException e){
               e.printStackTrace();
        }
        try{

            // Test options

        if(Line.hasOption("c")){
            //generating Zip
            for (int i = 2; i< args.length; i++){
                new ZipFile(args[1]).addFile(args[i]);
            }
        }
        else if (Line.hasOption("x")){



                //Extracting zip
                new ZipFile(args[1]).extractAll(args[2]);
        }else if( Line.hasOption("help"))
        {
            // Help manuel
            System.out.println(" compreser   -c [Destination] [File1] [File2] ......");
            System.out.println(" Decompreser -x [Source] [Destination]");

        }


        }catch ( ZipException e){ e.printStackTrace();}





    }
}
